### PR TITLE
Netcat and Label updates

### PR DESCRIPTION
**Pull request by Mendas88**
Included new Labels introduced in firmware v1.16 and replaced ncat commands with nc instead for compatibility with Home Assistant.

### CODE REVIEW

**Comment by foxharp** [comment]
Thanks!   I'll merge this, but I confess I have a few commits in my home repo to push, one of which changes the same area of code.  I'll be sure to keep this change in mind, though.

A question:  When you say "for compatibility with Home Assistant", I assume you just mean "because Home Assistant has the nc command, but not the ncat command".  Is that correct?

**Comment by Mendas88** [comment]
Correct, Home Assistant has the nc command, but not the ncat command. Currently tinkering, trying to get VE.Direct via USB data into HA. I guess you could leave the ncat commands, as it is a HA specific change, which might be out of scope - part of why I left the commands in the code commented out.

**Comment by foxharp** [comment]
It's complicated by the fact that HA uses busybox for most shell functions, and the busybox "nc" command doesn't support UNIX-domain sockets.  If it's the only command available, then local internet sockets could be used.  The code just has to choose a port number.  It's probably safe to do that on HA because I think they have network access pretty well firewalled.

To be clear:  will your USB VE.Direct device be plugged into the HA box?   It's probably not completely clear in the ve.direct script that the two client/server commands we're talking about run as a pair on the machine with the VE.Direct device.  Any "real" networking is done using ssh.  So if all you're doing is accessing an external machine from the HA box, you might not need to change those commands.

paul

**Comment by foxharp** [comment]
I've commited the labels change.

I've also pushed my changes for supporting ncat vs. socat.  But I tried using nc in various ways, and was unsuccessful.  My host isn't HA, but rather a raspberry Pi running the picoreplayer code.   But I do have HA running elsewhere, and the version of busybox is the same.

**Comment by foxharp** [comment]
(I cherry-picked your label changes manually and pushed to github, rather than learn how to properly do the merge right on github.)

**Comment by Mendas88** [comment]
I've used USB over IP to pass the VE.Direct USB to the HA container, which is working nicely.

I needed to make the nc/ncat changes to get the script to run initially. I'm slowly working through the script to better understand what each function does, because you're right, there will likely be several I do not need.

Its my first time trying to build anything for HA. You'd think something as simple as getting a voltage number from the VE.Direct into a HA sensor would have already been built by someone already, but everything I've found that ingests Victron data uses ESP.

**Comment by foxharp** [comment]
Nice trick with USB-over-IP.

If I were trying to do what you're attempting, I'd probably run my script outside of HA, at the source of the data, in standalone mode.  I'd modify the logging (or maybe, the "panel" routine) to write a copy of individual values to individual files -- i.e., one for voltage, one for current, etc, updated every time their value changes.  Then I'd use a RESTful listener on that same machine to make those values available on-demand to HA.  (I have a RESTful listener that lets HA query simple values from some temperature sensors that aren't managed directly by HA, and also lets external scripts respond to HA events like motion detection and zigbee remote control button presses.  Happy to share it if you'd like.)

**Comment by foxharp** [comment]
In fact, I liked that idea so much I just added a --statedir argument to ve.direct.

**Comment by Mendas88** [comment]
I'm running one of the inverters that sends very limited data over VE.Direct - no data on SOC of the battery, only voltage. 

I ended up modifying the script so that it grabs the battery's voltage and calculates/extrapolates the SOC based on several data points I've collected, and returns that % value. Its not a perfect measurement of the battery's SOC, but I can tolerate a +-5% margin for error in my use case - which is having the inverter shut off when the battery is reduced to approx 20% SOC. 

In HA, I've set up a command line sensor and automation takes care of the rest:
```
command_line:
  - sensor:
      name: Battery SOC
      unique_id: your_optional_id_goes_here_for_gui_interaction
      command: "bash ve.direct --raw --device=/dev/serial/by-id/usb-YOUR_DEVICE_HERE-port0"
      unit_of_measurement: "%"
      scan_interval: 60  # Time in seconds between updates
      value_template: "{{ value }}"
```
The BMS has a CAN port, so I will probably set up something in the future to get more accurate reads from the battery itself. But for what I need at the moment, this is working :)

**Comment by Mendas88** [comment]
Of course a consequence of relying on battery voltage as read by the inverter to determine SOC, it interprets the SOC as 100% the moment the battery starts to charge haha

**Comment by foxharp** [comment]
:-)   Hah!

Thanks for telling me about the "command_line:" sensor setup.  I didn't know that existed.  I also didn't know about the "unique_id:" field -- I wonder if that's available for REST sensors.  Being able manage them more properly in the GUI would be nice.

**Pull request closed without merging**
